window.SHIVRUDRA_CONFIG = {
  appsScriptUrl: "",
  company: {
    name: "Shivrudra Graphics Pvt Ltd",
    address: "Add your full company address in Settings",
    phone: "+91 90000 00000",
    email: "sales@shivrudragraphics.com",
    gstNumber: "",
    website: "www.shivrudragraphics.com"
  },
  defaults: {
    preparedBy: "Sales Desk",
    quotationValidityDays: 7,
    gstRate: 18,
    discountLimitPercent: 12,
    currency: "INR"
  },
  options: {
    industries: [
      "Retail",
      "Corporate",
      "Hospitality",
      "Real Estate",
      "Healthcare",
      "Education",
      "Events",
      "Automotive",
      "Manufacturing",
      "Government"
    ],
    qualities: ["Economy", "Premium"],
    printingTypes: ["Eco-solvent", "UV", "Offset", "Screen"],
    colorTypes: ["BW", "Color"],
    installationOptions: ["Yes", "No"],
    deliveryTypes: ["Pickup", "Local", "Outstation"],
    urgencyOptions: ["Normal", "Express"],
    followUpStatuses: [
      "Fresh Lead",
      "Awaiting Approval",
      "Follow-up Today",
      "Negotiation",
      "Won",
      "Lost"
    ],
    paymentStatuses: ["Pending", "Part Paid", "Paid"],
    roles: ["Sales", "Admin", "Accounts"]
  },
  presets: [
    {
      name: "Retail Launch Banner",
      category: "Printing",
      product: "Flex Banner",
      width: 4,
      height: 6,
      dimensionUnit: "ft",
      quantity: 3,
      materialType: "Star Flex",
      quality: "Premium",
      printingType: "Eco-solvent",
      colorType: "Color",
      finishing: ["Lamination", "Eyelets"],
      installationRequired: "Yes",
      deliveryType: "Local",
      urgency: "Normal",
      followUpStatus: "Awaiting Approval"
    },
    {
      name: "Corporate Stationery Pack",
      category: "Printing",
      product: "Visiting Cards",
      width: 3.5,
      height: 2,
      dimensionUnit: "inch",
      quantity: 500,
      materialType: "Art Card 350 GSM",
      quality: "Premium",
      printingType: "Offset",
      colorType: "Color",
      finishing: ["Lamination", "Cutting"],
      installationRequired: "No",
      deliveryType: "Pickup",
      urgency: "Express",
      followUpStatus: "Negotiation"
    },
    {
      name: "Branding Gift Batch",
      category: "Corporate Gifts",
      product: "Mug Branding",
      width: 3,
      height: 4,
      dimensionUnit: "inch",
      quantity: 100,
      materialType: "Ceramic Mug",
      quality: "Premium",
      printingType: "UV",
      colorType: "Color",
      finishing: ["Cutting"],
      installationRequired: "No",
      deliveryType: "Outstation",
      urgency: "Normal",
      followUpStatus: "Fresh Lead"
    }
  ],
  catalog: [
    {
      category: "Designing",
      product: "Logo Design",
      unitType: "order",
      description: "Concept development, brand marks, and master artwork for new or refreshed brands.",
      materials: ["Digital Files"]
    },
    {
      category: "Designing",
      product: "Brochure Layout",
      unitType: "page",
      description: "Marketing layout and artwork setup for brochures, catalogues, and printed handouts.",
      materials: ["Digital Files"]
    },
    {
      category: "Printing",
      product: "Flex Banner",
      unitType: "area",
      description: "Outdoor flex printing for launches, promotions, events, and shopfront campaigns.",
      materials: ["Star Flex", "Backlit Flex", "Blackout Flex"]
    },
    {
      category: "Printing",
      product: "Vinyl Sticker",
      unitType: "area",
      description: "Indoor and outdoor vinyl branding for glass, walls, and surfaces.",
      materials: ["Self Adhesive Vinyl", "One Way Vision", "Reflective Vinyl"]
    },
    {
      category: "Printing",
      product: "Visiting Cards",
      unitType: "unit",
      description: "High-volume business cards with premium stock and finishing options.",
      materials: ["Art Card 300 GSM", "Art Card 350 GSM", "Texture Card"]
    },
    {
      category: "Printing",
      product: "Brochure Printing",
      unitType: "unit",
      description: "Folded brochures and handouts for sales kits, exhibitions, and launches.",
      materials: ["Art Paper 170 GSM", "Art Paper 250 GSM", "Matt Paper 220 GSM"]
    },
    {
      category: "Signage",
      product: "ACP Sign Board",
      unitType: "area",
      description: "Durable ACP sign boards with branded print layers and site installation.",
      materials: ["ACP Panel 3 mm", "ACP Panel 4 mm", "Acrylic Face"]
    },
    {
      category: "Signage",
      product: "Glow Sign Board",
      unitType: "area",
      description: "Illuminated boards for retail, clinics, and hospitality properties.",
      materials: ["Acrylic Face", "LED Backlit", "Flex Face"]
    },
    {
      category: "Corporate Gifts",
      product: "Mug Branding",
      unitType: "unit",
      description: "Personalized ceramic mugs for gifting, HR kits, and brand recall campaigns.",
      materials: ["Ceramic Mug", "Magic Mug", "Steel Mug"]
    },
    {
      category: "Corporate Gifts",
      product: "T-Shirt Printing",
      unitType: "unit",
      description: "Promotional and staff apparel with durable print finishes.",
      materials: ["Cotton Tee", "Dry Fit Tee", "Polo Tee"]
    },
    {
      category: "Industrial",
      product: "Industrial Labels",
      unitType: "unit",
      description: "Machine labels, asset tags, and industrial branding labels.",
      materials: ["PVC Label", "Metal Label", "Polycarbonate Label"]
    },
    {
      category: "Fabrication",
      product: "Laser Cut Panel",
      unitType: "area",
      description: "Custom laser-cut fabrication panels for displays, gates, and branded structures.",
      materials: ["MS Sheet", "ACP Sheet", "Acrylic Sheet"]
    }
  ],
  pricingMaster: [
    {
      category: "Designing",
      product: "Logo Design",
      material: "Digital Files",
      unitType: "order",
      baseRate: 6500,
      materialCost: 1800,
      printCost: 0,
      installationCost: 0,
      minimumCharge: 6500,
      qualityAdjustments: { Economy: 0, Premium: 2200 },
      printingAdjustments: { "Eco-solvent": 0, UV: 0, Offset: 0, Screen: 0 },
      colorAdjustments: { BW: 0, Color: 0 }
    },
    {
      category: "Designing",
      product: "Brochure Layout",
      material: "Digital Files",
      unitType: "page",
      baseRate: 420,
      materialCost: 110,
      printCost: 0,
      installationCost: 0,
      minimumCharge: 2800,
      qualityAdjustments: { Economy: 0, Premium: 140 },
      printingAdjustments: { "Eco-solvent": 0, UV: 0, Offset: 0, Screen: 0 },
      colorAdjustments: { BW: 0, Color: 0 }
    },
    {
      category: "Printing",
      product: "Flex Banner",
      material: "Star Flex",
      unitType: "area",
      baseRate: 44,
      materialCost: 18,
      printCost: 9,
      installationCost: 14,
      minimumCharge: 600,
      qualityAdjustments: { Economy: 0, Premium: 6 },
      printingAdjustments: { "Eco-solvent": 0, UV: 8, Offset: 0, Screen: 4 },
      colorAdjustments: { BW: -4, Color: 0 }
    },
    {
      category: "Printing",
      product: "Flex Banner",
      material: "Backlit Flex",
      unitType: "area",
      baseRate: 58,
      materialCost: 26,
      printCost: 11,
      installationCost: 16,
      minimumCharge: 850,
      qualityAdjustments: { Economy: 0, Premium: 8 },
      printingAdjustments: { "Eco-solvent": 0, UV: 10, Offset: 0, Screen: 5 },
      colorAdjustments: { BW: -5, Color: 0 }
    },
    {
      category: "Printing",
      product: "Flex Banner",
      material: "Blackout Flex",
      unitType: "area",
      baseRate: 64,
      materialCost: 31,
      printCost: 12,
      installationCost: 18,
      minimumCharge: 920,
      qualityAdjustments: { Economy: 0, Premium: 8 },
      printingAdjustments: { "Eco-solvent": 0, UV: 11, Offset: 0, Screen: 6 },
      colorAdjustments: { BW: -6, Color: 0 }
    },
    {
      category: "Printing",
      product: "Vinyl Sticker",
      material: "Self Adhesive Vinyl",
      unitType: "area",
      baseRate: 66,
      materialCost: 30,
      printCost: 12,
      installationCost: 18,
      minimumCharge: 800,
      qualityAdjustments: { Economy: 0, Premium: 8 },
      printingAdjustments: { "Eco-solvent": 0, UV: 14, Offset: 0, Screen: 7 },
      colorAdjustments: { BW: -6, Color: 0 }
    },
    {
      category: "Printing",
      product: "Vinyl Sticker",
      material: "One Way Vision",
      unitType: "area",
      baseRate: 94,
      materialCost: 46,
      printCost: 16,
      installationCost: 20,
      minimumCharge: 980,
      qualityAdjustments: { Economy: 0, Premium: 10 },
      printingAdjustments: { "Eco-solvent": 0, UV: 16, Offset: 0, Screen: 8 },
      colorAdjustments: { BW: -8, Color: 0 }
    },
    {
      category: "Printing",
      product: "Vinyl Sticker",
      material: "Reflective Vinyl",
      unitType: "area",
      baseRate: 126,
      materialCost: 62,
      printCost: 18,
      installationCost: 24,
      minimumCharge: 1200,
      qualityAdjustments: { Economy: 0, Premium: 14 },
      printingAdjustments: { "Eco-solvent": 0, UV: 20, Offset: 0, Screen: 10 },
      colorAdjustments: { BW: -10, Color: 0 }
    },
    {
      category: "Printing",
      product: "Visiting Cards",
      material: "Art Card 300 GSM",
      unitType: "unit",
      baseRate: 4.4,
      materialCost: 1.5,
      printCost: 0.8,
      installationCost: 0,
      minimumCharge: 1800,
      qualityAdjustments: { Economy: 0, Premium: 0.6 },
      printingAdjustments: { "Eco-solvent": 0, UV: 0.9, Offset: 0, Screen: 0.4 },
      colorAdjustments: { BW: -0.5, Color: 0 }
    },
    {
      category: "Printing",
      product: "Visiting Cards",
      material: "Art Card 350 GSM",
      unitType: "unit",
      baseRate: 5.2,
      materialCost: 1.9,
      printCost: 0.9,
      installationCost: 0,
      minimumCharge: 2200,
      qualityAdjustments: { Economy: 0, Premium: 0.7 },
      printingAdjustments: { "Eco-solvent": 0, UV: 1.0, Offset: 0, Screen: 0.4 },
      colorAdjustments: { BW: -0.5, Color: 0 }
    },
    {
      category: "Printing",
      product: "Visiting Cards",
      material: "Texture Card",
      unitType: "unit",
      baseRate: 6.6,
      materialCost: 2.4,
      printCost: 1.0,
      installationCost: 0,
      minimumCharge: 2600,
      qualityAdjustments: { Economy: 0, Premium: 0.8 },
      printingAdjustments: { "Eco-solvent": 0, UV: 1.1, Offset: 0, Screen: 0.5 },
      colorAdjustments: { BW: -0.6, Color: 0 }
    },
    {
      category: "Printing",
      product: "Brochure Printing",
      material: "Art Paper 170 GSM",
      unitType: "unit",
      baseRate: 18,
      materialCost: 7,
      printCost: 3,
      installationCost: 0,
      minimumCharge: 3200,
      qualityAdjustments: { Economy: 0, Premium: 1.8 },
      printingAdjustments: { "Eco-solvent": 0, UV: 2.5, Offset: 0, Screen: 1.2 },
      colorAdjustments: { BW: -2.5, Color: 0 }
    },
    {
      category: "Printing",
      product: "Brochure Printing",
      material: "Art Paper 250 GSM",
      unitType: "unit",
      baseRate: 22,
      materialCost: 9,
      printCost: 3.4,
      installationCost: 0,
      minimumCharge: 3900,
      qualityAdjustments: { Economy: 0, Premium: 2.1 },
      printingAdjustments: { "Eco-solvent": 0, UV: 2.8, Offset: 0, Screen: 1.3 },
      colorAdjustments: { BW: -3.0, Color: 0 }
    },
    {
      category: "Printing",
      product: "Brochure Printing",
      material: "Matt Paper 220 GSM",
      unitType: "unit",
      baseRate: 24,
      materialCost: 10,
      printCost: 3.8,
      installationCost: 0,
      minimumCharge: 4200,
      qualityAdjustments: { Economy: 0, Premium: 2.2 },
      printingAdjustments: { "Eco-solvent": 0, UV: 3.0, Offset: 0, Screen: 1.5 },
      colorAdjustments: { BW: -3.2, Color: 0 }
    },
    {
      category: "Signage",
      product: "ACP Sign Board",
      material: "ACP Panel 3 mm",
      unitType: "area",
      baseRate: 240,
      materialCost: 120,
      printCost: 24,
      installationCost: 34,
      minimumCharge: 4800,
      qualityAdjustments: { Economy: 0, Premium: 26 },
      printingAdjustments: { "Eco-solvent": 0, UV: 22, Offset: 0, Screen: 12 },
      colorAdjustments: { BW: -12, Color: 0 }
    },
    {
      category: "Signage",
      product: "ACP Sign Board",
      material: "ACP Panel 4 mm",
      unitType: "area",
      baseRate: 275,
      materialCost: 142,
      printCost: 26,
      installationCost: 36,
      minimumCharge: 5200,
      qualityAdjustments: { Economy: 0, Premium: 30 },
      printingAdjustments: { "Eco-solvent": 0, UV: 24, Offset: 0, Screen: 12 },
      colorAdjustments: { BW: -14, Color: 0 }
    },
    {
      category: "Signage",
      product: "ACP Sign Board",
      material: "Acrylic Face",
      unitType: "area",
      baseRate: 320,
      materialCost: 174,
      printCost: 28,
      installationCost: 38,
      minimumCharge: 6400,
      qualityAdjustments: { Economy: 0, Premium: 34 },
      printingAdjustments: { "Eco-solvent": 0, UV: 28, Offset: 0, Screen: 14 },
      colorAdjustments: { BW: -16, Color: 0 }
    },
    {
      category: "Signage",
      product: "Glow Sign Board",
      material: "Acrylic Face",
      unitType: "area",
      baseRate: 360,
      materialCost: 196,
      printCost: 30,
      installationCost: 42,
      minimumCharge: 7600,
      qualityAdjustments: { Economy: 0, Premium: 40 },
      printingAdjustments: { "Eco-solvent": 0, UV: 30, Offset: 0, Screen: 15 },
      colorAdjustments: { BW: -18, Color: 0 }
    },
    {
      category: "Signage",
      product: "Glow Sign Board",
      material: "LED Backlit",
      unitType: "area",
      baseRate: 420,
      materialCost: 240,
      printCost: 32,
      installationCost: 48,
      minimumCharge: 8900,
      qualityAdjustments: { Economy: 0, Premium: 46 },
      printingAdjustments: { "Eco-solvent": 0, UV: 34, Offset: 0, Screen: 16 },
      colorAdjustments: { BW: -20, Color: 0 }
    },
    {
      category: "Signage",
      product: "Glow Sign Board",
      material: "Flex Face",
      unitType: "area",
      baseRate: 305,
      materialCost: 156,
      printCost: 24,
      installationCost: 40,
      minimumCharge: 6200,
      qualityAdjustments: { Economy: 0, Premium: 28 },
      printingAdjustments: { "Eco-solvent": 0, UV: 26, Offset: 0, Screen: 12 },
      colorAdjustments: { BW: -14, Color: 0 }
    },
    {
      category: "Corporate Gifts",
      product: "Mug Branding",
      material: "Ceramic Mug",
      unitType: "unit",
      baseRate: 130,
      materialCost: 62,
      printCost: 14,
      installationCost: 0,
      minimumCharge: 2800,
      qualityAdjustments: { Economy: 0, Premium: 12 },
      printingAdjustments: { "Eco-solvent": 0, UV: 8, Offset: 0, Screen: 4 },
      colorAdjustments: { BW: -8, Color: 0 }
    },
    {
      category: "Corporate Gifts",
      product: "Mug Branding",
      material: "Magic Mug",
      unitType: "unit",
      baseRate: 190,
      materialCost: 96,
      printCost: 18,
      installationCost: 0,
      minimumCharge: 4200,
      qualityAdjustments: { Economy: 0, Premium: 14 },
      printingAdjustments: { "Eco-solvent": 0, UV: 10, Offset: 0, Screen: 5 },
      colorAdjustments: { BW: -10, Color: 0 }
    },
    {
      category: "Corporate Gifts",
      product: "Mug Branding",
      material: "Steel Mug",
      unitType: "unit",
      baseRate: 220,
      materialCost: 116,
      printCost: 20,
      installationCost: 0,
      minimumCharge: 5000,
      qualityAdjustments: { Economy: 0, Premium: 16 },
      printingAdjustments: { "Eco-solvent": 0, UV: 12, Offset: 0, Screen: 6 },
      colorAdjustments: { BW: -10, Color: 0 }
    },
    {
      category: "Corporate Gifts",
      product: "T-Shirt Printing",
      material: "Cotton Tee",
      unitType: "unit",
      baseRate: 250,
      materialCost: 120,
      printCost: 28,
      installationCost: 0,
      minimumCharge: 3000,
      qualityAdjustments: { Economy: 0, Premium: 18 },
      printingAdjustments: { "Eco-solvent": 0, UV: 14, Offset: 0, Screen: 8 },
      colorAdjustments: { BW: -12, Color: 0 }
    },
    {
      category: "Corporate Gifts",
      product: "T-Shirt Printing",
      material: "Dry Fit Tee",
      unitType: "unit",
      baseRate: 290,
      materialCost: 148,
      printCost: 32,
      installationCost: 0,
      minimumCharge: 3600,
      qualityAdjustments: { Economy: 0, Premium: 20 },
      printingAdjustments: { "Eco-solvent": 0, UV: 16, Offset: 0, Screen: 8 },
      colorAdjustments: { BW: -12, Color: 0 }
    },
    {
      category: "Corporate Gifts",
      product: "T-Shirt Printing",
      material: "Polo Tee",
      unitType: "unit",
      baseRate: 340,
      materialCost: 176,
      printCost: 36,
      installationCost: 0,
      minimumCharge: 4200,
      qualityAdjustments: { Economy: 0, Premium: 24 },
      printingAdjustments: { "Eco-solvent": 0, UV: 18, Offset: 0, Screen: 9 },
      colorAdjustments: { BW: -14, Color: 0 }
    },
    {
      category: "Industrial",
      product: "Industrial Labels",
      material: "PVC Label",
      unitType: "unit",
      baseRate: 12,
      materialCost: 4.8,
      printCost: 1.8,
      installationCost: 0,
      minimumCharge: 2500,
      qualityAdjustments: { Economy: 0, Premium: 1.4 },
      printingAdjustments: { "Eco-solvent": 0, UV: 1.2, Offset: 0, Screen: 0.6 },
      colorAdjustments: { BW: -1.2, Color: 0 }
    },
    {
      category: "Industrial",
      product: "Industrial Labels",
      material: "Metal Label",
      unitType: "unit",
      baseRate: 26,
      materialCost: 11.2,
      printCost: 2.5,
      installationCost: 0,
      minimumCharge: 4200,
      qualityAdjustments: { Economy: 0, Premium: 2.2 },
      printingAdjustments: { "Eco-solvent": 0, UV: 2.0, Offset: 0, Screen: 1.0 },
      colorAdjustments: { BW: -1.6, Color: 0 }
    },
    {
      category: "Industrial",
      product: "Industrial Labels",
      material: "Polycarbonate Label",
      unitType: "unit",
      baseRate: 31,
      materialCost: 13.6,
      printCost: 2.9,
      installationCost: 0,
      minimumCharge: 4800,
      qualityAdjustments: { Economy: 0, Premium: 2.4 },
      printingAdjustments: { "Eco-solvent": 0, UV: 2.2, Offset: 0, Screen: 1.1 },
      colorAdjustments: { BW: -1.8, Color: 0 }
    },
    {
      category: "Fabrication",
      product: "Laser Cut Panel",
      material: "MS Sheet",
      unitType: "area",
      baseRate: 285,
      materialCost: 136,
      printCost: 12,
      installationCost: 42,
      minimumCharge: 5400,
      qualityAdjustments: { Economy: 0, Premium: 26 },
      printingAdjustments: { "Eco-solvent": 0, UV: 10, Offset: 0, Screen: 0 },
      colorAdjustments: { BW: 0, Color: 0 }
    },
    {
      category: "Fabrication",
      product: "Laser Cut Panel",
      material: "ACP Sheet",
      unitType: "area",
      baseRate: 315,
      materialCost: 154,
      printCost: 14,
      installationCost: 44,
      minimumCharge: 6000,
      qualityAdjustments: { Economy: 0, Premium: 30 },
      printingAdjustments: { "Eco-solvent": 0, UV: 12, Offset: 0, Screen: 0 },
      colorAdjustments: { BW: 0, Color: 0 }
    },
    {
      category: "Fabrication",
      product: "Laser Cut Panel",
      material: "Acrylic Sheet",
      unitType: "area",
      baseRate: 355,
      materialCost: 180,
      printCost: 16,
      installationCost: 48,
      minimumCharge: 6800,
      qualityAdjustments: { Economy: 0, Premium: 34 },
      printingAdjustments: { "Eco-solvent": 0, UV: 14, Offset: 0, Screen: 0 },
      colorAdjustments: { BW: 0, Color: 0 }
    }
  ],
  finishingRates: {
    Lamination: {
      area: { sell: 9, cost: 4 },
      unit: { sell: 1.8, cost: 0.8 },
      order: { sell: 180, cost: 70 }
    },
    Mounting: {
      area: { sell: 24, cost: 13 },
      unit: { sell: 2.4, cost: 1.2 },
      order: { sell: 300, cost: 160 }
    },
    Cutting: {
      area: { sell: 6, cost: 2 },
      unit: { sell: 0.8, cost: 0.3 },
      order: { sell: 120, cost: 48 }
    },
    Framing: {
      area: { sell: 32, cost: 18 },
      unit: { sell: 8, cost: 4.5 },
      order: { sell: 420, cost: 220 }
    },
    Binding: {
      area: { sell: 0, cost: 0 },
      unit: { sell: 12, cost: 5.5 },
      order: { sell: 180, cost: 84 }
    },
    Eyelets: {
      area: { sell: 4.5, cost: 1.8 },
      unit: { sell: 1.2, cost: 0.4 },
      order: { sell: 96, cost: 36 }
    }
  },
  deliveryCharges: {
    Pickup: { sell: 0, cost: 0 },
    Local: { sell: 350, cost: 180 },
    Outstation: { sell: 1350, cost: 940 }
  },
  urgencyMultipliers: {
    Normal: 1,
    Express: 1.18
  },
  industryMultipliers: {
    Retail: 1,
    Corporate: 1.05,
    Hospitality: 1.04,
    "Real Estate": 1.03,
    Healthcare: 1.02,
    Education: 0.98,
    Events: 1.06,
    Automotive: 1.04,
    Manufacturing: 1.01,
    Government: 1.02
  },
  terms: [
    "Quotation validity is subject to pricing confirmation and raw material availability.",
    "Standard production begins after artwork approval and advance confirmation.",
    "Transportation, taxes, and site conditions may affect final dispatch timelines.",
    "Invoices become payable as per agreed commercial terms."
  ]
};
